[package]
name = "move-prover"
version = "1.0.0"
authors = []

[addresses]
test="_"

[dev-addresses]
test="0x1234"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
