[package]
name = "move-prover"
version = "1.0.0"
authors = []

[addresses]
prover="_"

[dev-addresses]
prover="ff4d99d8994045359736c89f8a5e34f0c01a098913f32829767c6d9954fa135f"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
