[package]
name = "rotate-resource-account-auth-key"
version = "1.0.0"
authors = []

[addresses]
addr="_"

[dev-addresses]
addr="679f214e1a1e0b4341f55990c0ff2a514a63cf5a9a5b76c66ff6ac195f0fa220"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
